# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-eddcceff-290e-478d-baef-3fdc0f47a220";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-eddcceff-290e-478d-baef-3fdc0f47a220".device = "/dev/disk/by-uuid/eddcceff-290e-478d-baef-3fdc0f47a220";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A23-C86E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-5f5524e7-c2c0-4cbd-91f2-37b8fe69a62c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
